### ISSUE TITLE
Server Error 500 When Entering a Very Large Capacity Number

### ISSUE THREAD

**Issue by SunthornK** [pannlnwza/queue-management#197] opened 2024-11-24 15:53 UTC
Entering a very large number in the capacity field during queue creation causes a 500 Server Error.
![image](https://github.com/user-attachments/assets/243462d9-1d9c-4460-9574-a788d4a19685)
![image](https://github.com/user-attachments/assets/25210c56-801d-40a6-9a4c-b19b7d47dbaf)

**Comment by pannlnwza** [comment] 2024-12-02 18:37
Thanks for pointing out! This is a duplicate of [#194](https://github.com/pannlnwza/queue-management/issues/194), and we’ve already fixed it by limiting the maximum capacity

**Closed by pannlnwza** 2024-12-02 18:37 UTC
Labels: bug
